import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) throw new Error("DATABASE_URL is required");
const pool = new pg.Pool({ connectionString, max: 2 });

type ColumnRow = { column_name: string };
type IndexRow = { indexname: string; indexdef: string };
type ForeignKeyRow = {
  table_name: string;
  column_name: string;
  foreign_table_name: string;
  foreign_column_name: string;
};
const MIGRATION_TABLES = new Set(["kysely_migration", "kysely_migration_lock"]);

async function getTables() {
  const result = await pool.query<{ tablename: string }>(
    "SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname = $1 ORDER BY tablename",
    ["public"],
  );
  return result.rows.map((row) => row.tablename).filter((table) => !MIGRATION_TABLES.has(table));
}

async function getColumns(table: string) {
  return (
    await pool.query<ColumnRow>(
      `SELECT column_name FROM information_schema.columns
       WHERE table_schema = $1 AND table_name = $2 ORDER BY ordinal_position`,
      ["public", table],
    )
  ).rows;
}

async function getIndexes(table: string) {
  return (
    await pool.query<IndexRow>(
      `SELECT indexname, indexdef FROM pg_indexes
       WHERE schemaname = $1 AND tablename = $2 ORDER BY indexname`,
      ["public", table],
    )
  ).rows;
}

async function getForeignKeys() {
  return (
    await pool.query<ForeignKeyRow>(
      `SELECT tc.table_name, kcu.column_name, ccu.table_name AS foreign_table_name,
         ccu.column_name AS foreign_column_name
       FROM information_schema.table_constraints tc
       JOIN information_schema.key_column_usage kcu
         ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
       JOIN information_schema.constraint_column_usage ccu
         ON ccu.constraint_name = tc.constraint_name AND ccu.table_schema = tc.table_schema
       WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = $1
       ORDER BY tc.table_name, kcu.column_name`,
      ["public"],
    )
  ).rows;
}

function formatIndex(indexRow: IndexRow, primaryKeys: Set<string>) {
  if (primaryKeys.has(indexRow.indexname)) return null;
  const columns = indexRow.indexdef.match(/\(([^)]+)\)/)?.[1]?.trim() ?? "";
  return `- ${/CREATE UNIQUE INDEX/i.test(indexRow.indexdef) ? "unique " : ""}\`${indexRow.indexname}\` on \`${columns}\``;
}

async function buildMarkdown() {
  const lines = [
    "# Database Schema",
    "",
    "Generated by `pnpm db:snapshot`. Do not edit by hand.",
    "",
    "## Global Rules",
    "",
    "- SQL tables are singular.",
    "- SQL columns use `snake_case`.",
    "- TypeScript schema properties use `camelCase`.",
    '- Quote `"user"` in raw SQL because `user` is reserved in PostgreSQL.',
    "- Store JSON arrays under an object key, for example `{ files: [...] }`.",
    "",
    "## Tables",
    "",
  ];

  for (const table of await getTables()) {
    const columns = await getColumns(table);
    const indexes = await getIndexes(table);
    const primaryKeys = new Set(
      indexes.filter((row) => row.indexname.endsWith("_pkey")).map((row) => row.indexname),
    );
    lines.push(`### \`${table}\``, "", "Columns:", "");
    for (const column of columns) lines.push(`- \`${column.column_name}\``);
    lines.push("");
    const indexLines = indexes
      .map((row) => formatIndex(row, primaryKeys))
      .filter((line): line is string => line !== null);
    if (indexLines.length) lines.push("Indexes:", "", ...indexLines, "");
  }

  lines.push("## Relationships", "");
  const foreignKeys = await getForeignKeys();
  if (!foreignKeys.length) lines.push("_No foreign keys defined._");
  for (const foreignKey of foreignKeys) {
    lines.push(
      `- \`${foreignKey.table_name}.${foreignKey.column_name}\` -> \`${foreignKey.foreign_table_name}.${foreignKey.foreign_column_name}\``,
    );
  }
  lines.push("");
  return lines.join("\n");
}

const outputPath = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../docs/db-schema.md",
);
try {
  await writeFile(outputPath, await buildMarkdown(), "utf8");
  console.log(`Wrote ${outputPath}`);
} finally {
  await pool.end();
}
